---
- name: Install Docker on all nodes
  hosts: ubuntu
  become: true
  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes

    - name: Install prerequisite packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Add Docker's official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Install Docker Engine
      apt:
        name: docker-ce
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Install Docker SDK for Python
      apt:
        name: python3-docker
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Ensure Docker service is started and enabled on boot
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

- hosts: centos
  become: true
  tasks:

    - name: Update YUM package cache
      yum:
        update_cache: yes

    - name: install prerequisites
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present

    - name: add docker repo
      command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    - name: install docker
      yum:
        name: docker-ce
        state: present

    - name: start docker
      systemd:
        name: docker
        state: started
        enabled: yes
