---
- hosts: all
  become: true
  tasks:

    - name: Copy website files to server
      copy:
        src: website/
        dest: /SYS AD FINALS/website/
        owner: root
        group: root
        mode: '0755'

    - name: build docker image (ubuntu)
      community.docker.docker_image:
        name: portfolio_site
        build:
          path: /SYS AD FINALS/website
        source: build
      when: ansible_distribution == "Ubuntu"

    - name: build docker image (centos)
      community.docker.docker_image:
        name: portfolio_site
        build:
          path: /SYS AD FINALS/website
        source: build
        docker_host: tcp://192.168.56.104:2375
      when: ansible_distribution == "CentOS"

    - name: run website container (ubuntu)
      community.docker.docker_container:
        name: portfolio_site
        image: portfolio_site
        state: started
        restart_policy: always
        published_ports:
          - "8080:80"
      when: ansible_distribution == "Ubuntu"

    - name: run website container (centos)
      community.docker.docker_container:
        name: portfolio_site
        image: portfolio_site
        state: started
        restart_policy: always
        published_ports:
          - "8080:80"
        docker_host: tcp://192.168.56.104:2375
      when: ansible_distribution == "CentOS"
